### ISSUE TITLE
Linux build doesn't load correctly

### ISSUE THREAD

**Issue by patataofcourse** [Meorge/sneaksters-testing#122]
After the "Photon PUN" and "Made with Unity" screen shows up, this is all I see.
My PC also lagged significantly.
![image](https://user-images.githubusercontent.com/29714419/92334446-4a40bb80-f08e-11ea-92b9-c65a887e9d68.png)

**Comment by Meorge** [comment]
It sounds like this is due to FMOD being outdated: https://qa.fmod.com/t/unity-2019-3-0f6-err-header-mismatch/15427/32

I will try updating the version of FMOD used in *Sneaksters* for v0.3.1 and we'll see if it works then.

**Comment by Meorge** [comment]
Ok, I think this has been fixed for v0.3.1? I've updated FMOD to version v2.0.10, which was released on July 21, 2020; the fix was supposedly in the v2.01.01 of the Studio API, which came out on May 12, 2020, so it should fix the problem. I'm going to close the issue for now since the fix should be implemented, but we can certainly reopen it if it comes up again.
