### ISSUE TITLE
[Linux] Pause menu buttons don't work

### ISSUE THREAD

**Issue by patataofcourse** [Meorge/sneaksters-testing#134]
Both in Thief and Eye. Linux 0.3.1 build, Manjaro 20.0.3 live USB
![image](https://user-images.githubusercontent.com/29714419/93523834-e8a50a80-f933-11ea-94d4-9becf5a43bb1.png)

**Comment by patataofcourse** [comment]
Uh, nevermind, apparently neither button works. Tab still does after pressing them.

**Comment by Meorge** [comment]
This has been half-fixed for v0.3.2. There are definitely still issues to fix with the status/pause menu, which I'll work on in separate issue(s):
- For some weird reason, while the WASD keys correctly switch between the "Resume" and "Leave Mission" buttons, the arrow keys are inverted - when the "Resume" button is selected, you have to press Up in order to move the selection *down* to the "Leave Mission" button, and vice versa.
- It's not super easy to tell which button is selected, since it uses a color tint. In the future (perhaps v0.3.3), I'd like to change this so that it has "corner pieces" like the main menu UI buttons.
