### ISSUE TITLE
Level 1 - getting caught after getting 1 gem softlocked the game

### ISSUE THREAD

**Issue by ZeldaPlayer29** [Meorge/sneaksters-testing#142]
Windows v0.3.1

See screenshot:
![image](https://user-images.githubusercontent.com/55148125/93875832-a54cf200-fccd-11ea-92ad-8e64e2d19530.png)

After collecting one gem (which opened the exit for debug reasons, as discussed elsewhere) and getting caught the game effectively froze - I couldn't move my camera or the player, and the game didn't return to the menu. The guards continued moving around the map but they ignored me.

**Comment by Meorge** [comment]
Game-breaking bugs like these are definitely very important, and I'd like to get them fixed ASAP. I'll try to do a little bit of debugging and see if I can find a solution in the next day or two. If not, I think I'm going to release v0.3.2 with some better debug statements and such, and try to diagnose the issue from there.

**Comment by Meorge** [comment]
I think I've figured out at least *part of* why this is happening, and honestly now I have no idea how the code worked in the first place (if it ever did). The "thief got caught" event gets called on everyone's computers, but only on the player object who actually got caught, or something like that... everything uses RPCs, instead of player properties or events which would be better. I'm going to close this for now, and in v0.3.3 I think I'm going to try and rework this whole thing so that it's safer and more efficient.

**Comment by Meorge** [comment]
v0.3.3 now uses PlayerProperties for this stuff, which should hopefully make it more stable!
