### ISSUE TITLE
Sneaksters won't load

### ISSUE THREAD

**Issue by patataofcourse** [Meorge/sneaksters-testing#166]
Windows 10, v0.3.5, game loaded from a FAT32 flash drive.
The game crashes before even starting. Pretty sure it's not an antivirus issue, since Sneaksters.exe was left untouched and the game actually got to boot?
Sent you log thru DMs.

**Comment by Meorge** [comment]
It's possible that this has to do with the override for the expiration check, since the message "Se ha intentado tener acceso a una dirección no válida" ("An attempt was made to access an invalid address") appears in the log, but that could also well be referring to, like, a segmentation fault kind of issue. If it's the latter, I have no idea how I'd fix that - probably a Unity bug. Can you try loading the game from the hard drive instead of a flash drive?

**Comment by patataofcourse** [comment]
It seems to have the same issue, do I send you this log?

**Comment by Meorge** [comment]
That would be helpful, thanks!

**Comment by Meorge** [comment]
More investigation suggests it *may* have to do with Unity and AMD graphics drivers problems:
```
aticfx64.dll caused an Access Violation (0xc0000005)
  in module aticfx64.dll at 0033:d88ff41e.
```

**Comment by Meorge** [comment]
Since it's not an issue I can handle on my end, I'm going to close it for now
