### ISSUE TITLE
Some issues regarding the step SFX

### ISSUE THREAD

**Issue by patataofcourse** [Meorge/sneaksters-testing#18]
-It keeps sounding after the game ends, until reappearing in the squad settings, which sounds like a heartbeat and gives the sensations of not actually being safe... creepy. (Windows, every build)
-Shouldn't it sound more times when running and less when walking tired? It feels weird.

**Comment by Meorge** [comment]
I'm pretty sure I know why this happens. My recollection is that the footstep sound effects are tied to the walking animation, such that a single sound plays at the same time that the foot touches the ground in the animation.

The sound persisting after the game ends is probably just because the animator never gets told "ok you don't need to animate anymore" and just remembers the last thing the Thief was doing was walking, so it continues to play the walking animation and thus makes the walking sounds.

However, there aren't separate animations for running, walking, and walking when tired out (nor does the speed of the animation change), so no matter what speed you're moving the feet are "touching" the ground at the same time, and the sound plays at the same rate.


That being said - I have to say I kinda like what you were saying with it sounding like a heartbeat. It definitely doesn't make sense in the context of escaping, but perhaps we could work something in like that for when a Guard is nearby... ;)

**Comment by Meorge** [comment]
The speed of the walking animation (and the footstep frequency) now changes depending on your speed! I'm hoping to fix the "footsteps continuing" bug soon as well.

**Comment by Meorge** [comment]
Fixed the "footsteps continuing" bug!
