### ISSUE TITLE
Change name in credits

### ISSUE THREAD

**Issue by ZeldaPlayer29** [Meorge/sneaksters-testing#186]
Opening this here because I don't think GitHub allows for DMs-
Can I have my name in the credits updated to read "ZeldaPlayer29", please? For privacy reasons. Thanks.

**Comment by ZeldaPlayer29** [comment]
Ok, I'm an idiot, I was going to contact you privately on Twitter about this as I thought that might be easier, but I don't think I can do that.

**Comment by Meorge** [comment]
Hi, sorry about the delay!
I can (and just did) update the CREDITS.md file that will be released with future versions of Sneaksters, as well as the README.md file for this repository. Unfortunately, though, due to the way Git and GitHub work, there's no way for me to scrub your name completely from the history - so it may still be possible for people to find it by searching through previous versions of the repository.

**Comment by ZeldaPlayer29** [comment]
Thanks!
