### ISSUE TITLE
"This build of Sneaksters expired 15 days ago."

### ISSUE THREAD

**Issue by DodoLeDev** [Meorge/sneaksters-testing#187]
### Hello everyone!
**I'm brand new to Sneaksters, a game I'd love to contribute too!**

However, I can't start the game without encountering this error. What should I do?

![Sneaksters_WA6ZOUhLKb](https://user-images.githubusercontent.com/59477313/114862357-b76bba80-9dee-11eb-9db4-dfe0a6fe7ed5.png)

System configuration
> Windows 10, build 20H2
> Sneaksters v0.4.4 alpha
> Time of test : 13:35, 2021-04-15

*Thanks again in advance (this is my very first contribution to a public repository)!*

**Comment by Meorge** [comment]
Hi, and thanks for wanting to contribute! :)
This is an issue on my end of things - the expiration date for the build was apparently March 31, 2021. I'll try to see if I can release a build with the expiration date extended farther (or perhaps just removed) this weekend.

**Comment by DodoLeDev** [comment]
Hi!
Thanks for your quick response! I'll look forward to the weekend!

*So I will close this issue...*

**Comment by Meorge** [comment]
I had some extra time during one of my classes today, and the game-being-expired issue was weighing on me a lot, so I went and made a new set of builds that have the expiration date restriction removed! https://github.com/Meorge/sneaksters-testing/releases/tag/v0.4.5-prealpha

**Comment by DodoLeDev** [comment]
## It works!
**Big thanks!**
And by the way, your game is awesome!

*However, the French translations need to be worked a bit more...*
That's why I will contribute to it!

**Comment by Meorge** [comment]
Thanks, I'm glad you like it! :)

The translations currently in the game are from quite a while ago - since they were done, I've been making a lot of changes to the game, and as such they haven't been a high priority item. At some point soonish I will probably need to rework how translations are implemented and available for people to contribute to. As such, please don't feel any rush to edit the translation files right now, as they'll likely become obsolete soon.

If you're not there already and have a Discord account, there is also a [Discord server](https://discord.gg/4EERzCj) where I post new builds and information about the game, and where players can coordinate to play the game together!
