### ISSUE TITLE
Button Prompts not Displaying Correctly

### ISSUE THREAD

**Issue by ZeldaPlayer29** [Meorge/sneaksters-testing#188]
It has been observed that the "Move Out!" button string displays as "ENTER Move Out!", not fitting into the button properly. It is expected that the button would read "Move Out!", maybe with a smaller ENTER prompt underneath the button or somewhere less intrusive.

Environment:
Windows 10 64-bit

Version:
v0.4.5 Pre-Alpha

Persistence:
100% - Consistently Reproducible

Supporting Material:
![image](https://user-images.githubusercontent.com/55148125/115118255-33563600-9f9a-11eb-8769-f8cfd8db6da5.png)

Severity:
Cosmetic

**Comment by ZeldaPlayer29** [comment]
(It's been a while since I've tested Sneaksters, and I think there may've been a similar issue in the past - but I'm not too sure).

**Comment by ghost** [comment]
Also noticed that button prompts display as "{{Action}}". Additionally, all menu buttons show text for all platforms after completing a game. Button prompts should display the button for the user to use in gameplay, and only the user's platform should be referenced.

![image](https://user-images.githubusercontent.com/55148125/115118498-53d2c000-9f9b-11eb-9383-406002a7b181.png)
![image](https://user-images.githubusercontent.com/55148125/115118654-29cdcd80-9f9c-11eb-992a-d062646cddda.png)

**Comment by Meorge** [comment]
Thanks for the report. Could you send me your `Player.log` file? I should be able to use information from it to update the button prompts so that they are correctly triggered.

**Comment by ZeldaPlayer29** [comment]
[Player.log](https://github.com/Meorge/sneaksters-testing/files/6329556/Player.log)
No problem. I have attached the log to this comment.

**Comment by Meorge** [comment]
I'm guessing this is the case, but just to make sure: you didn't connect or disconnect any other controllers while playing?

**Comment by ZeldaPlayer29** [comment]
No, just the keyboard and mouse. It's possibly related to starting or ending a game, as the issue with "{{Action}}" can only really be observed after starting a game, and the multiple controller prompts specifically started happening after ending a game (but could've maybe been triggered after starting the game - no way of checking that in-game).

**Comment by ZeldaPlayer29** [comment]
The issue with the multiple controller prompts also happens when either winning a game or getting a game over - see videos of both.

https://user-images.githubusercontent.com/55148125/115120036-30ac0e80-9fa3-11eb-907b-326d84a8b182.mp4

https://user-images.githubusercontent.com/55148125/115120039-34d82c00-9fa3-11eb-9a52-85fa8173417b.mp4

**Comment by Meorge** [comment]
Thanks for the videos and other resources documenting the bugs - I really appreciate them!

I'm able to reproduce the issue on my end as well. I've gotten it to be a lot better, but it's still having some issues. It appears that when the gameplay scene is entered, it detects the keyboard and mouse as being disconnected, and as such decides that you must now be using *all* of the controller types at the same time (because that's only natural, right? :P )

![Sneaksters Screenshot at 2021-04-17 09:57:46](https://user-images.githubusercontent.com/9957987/115120804-3df5d880-9f64-11eb-97a9-993f9eb112a5.png)
![Sneaksters Screenshot at 2021-04-17 09:58:10](https://user-images.githubusercontent.com/9957987/115120807-40f0c900-9f64-11eb-8b27-f9499a6a4e20.png)
<img width="644" alt="Screen Shot 2021-04-17 at 10 04 50 AM" src="https://user-images.githubusercontent.com/9957987/115120893-b65c9980-9f64-11eb-83c6-a92e2f52eb12.png">

I'm going to have to dig into that whole mess a bit later, since I need to work on school stuff, but at least for now the names-of-controllers-spanning-the-screen issue seems to be resolved and will come out with the next update, assuming nothing explodes before then.

**Comment by Meorge** [comment]
I've updated the InputHints library to be independent of system language, so this issue should hopefully maybe be fixed! Rather than try to bundle in other bug fixes, I think I'm just going to release v0.4.6 with this change and see how that goes.
