### ISSUE TITLE
Some new bugs I've encountered in Sneaksters

### ISSUE THREAD

**Issue by DodoLeDev** [Meorge/sneaksters-testing#191]
## Hi! I'm here to share some new bugs I've encountered while using Sneaksters.
Before I begin, I would like to point out that the game runs on the following system configuration:
> Windows 10 version 20H2
> Keyboard and System language : French
> Game language : English (The only one who has the small icons!)
> Game version : v0.4.5 Pre-Alpha
I have attached a video to this message to provide a concrete example of the bugs I have encountered 

Identified bugs:
- As you probably know, there is a bug with the display of emotes next to the quick messages which show something like `@@{Gameplay/EmoteX}` (00:27)
- In addition, there is a collision bug with collected diamonds that disappear into walls when dropped when our backs are against a wall (01:06)
- Finally, I encounter a connection bug to the servers after leaving or finishing a game while the presence of a ping shows me that I am still connected to the Internet... (01:25)

https://user-images.githubusercontent.com/59477313/115702105-cd3a2c00-a368-11eb-88f8-7eb64d0128ce.mp4

**Comment by Meorge** [comment]
Thank you for the reports!

* The first bug with `@@Gameplay/EmoteX}` will be fixed in the next version
* It's strange that the Gemstone didn't respawn after you dropped it through the wall... I've known about the ability to drop them through walls, but when that is done, they should fall a certain distance then respawn at their original location. However, I didn't see it respawn in your video before you exited the level (which should've been enough time, I think?) You don't need to record a video, but could you try playing again, dropping the Gemstone through the wall, and then waiting several seconds to see if it reappears at the original location?
* The third bug is something that's plagued the game for a while, and I hope to dig into it deeper soon.

I'm going to close this issue for now and open the second and third reports as separate issues so I can keep better track of them.
