### ISSUE TITLE
Some suggestions to make the game experience more understandable & intuitive to beginners

### ISSUE THREAD

**Issue by DodoLeDev** [Meorge/sneaksters-testing#192]
Hi! It's me again! 😁
This time I am here to share some rather practical suggestions...

Before I begin, I would like to point out that the game runs on the following system configuration:
> Windows 10 version 20H2
> Keyboard and System language : French
> Game language : English (The only one who has the small icons!)
> Game version : v0.4.5 Pre-Alpha

In order to make the game more understandable to beginners and also to avoid ending up in endless games, here is what I propose :
- You could disable the "Move Out!" button when no player is a thief, because the game cannot end if no one is present to collect the diamonds...
- You could disable the game launch if a map where the hacker is needed has been chosen while nobody in the team is a hacker, because it becomes impossible to go any further if no one can open the locked doors...
- You could add the escape button in the commands to go back, in addition to the right click, for people who want to navigate by keyboard only

*That's it! That's all I have to suggest at the moment... I hope I've helped you!*

**Comment by Meorge** [comment]
Thank you for the suggestions!

* The idea to disable to "Move Out!" button when no players are Thieves is a good one, and definitely something I'll do for a final release. However, it simplifies the process of testing since it allows us to play as Hackers without needing another copy of the game running as a Thief. I opened an issue for this a long time ago (#15) but eventually closed it because it doesn't soft- or hard-lock the game (players can use the Tab pause menu to return to the main menu), and there were other things to work on. In a future release, I may have the "Move Out!" button disabled by default, but become enabled if a specific setting is toggled.

* I don't see an issue logged regarding the launching-maps-where-Hackers-are-required problem, but I definitely also remember thinking about that and how to address it. The reason I haven't done something like that yet is more or less the same as the "Move Out!" button (makes debugging easier). I think a good solution to this in the meantime may be to add a warning indicator to levels that require Hackers when no Hackers are currently in the squad (maybe this could also be applied to the "Move Out!" button?)

* Having the Escape button be usable to go back makes a lot of sense, and I'm not sure why that wasn't already the case. Regardless, it's now set so that the Escape key can be used, and should be out with the next release! :)
