### ISSUE TITLE
Game gets detected as virus (IDP.Generic)

### ISSUE THREAD

**Issue by patataofcourse** [Meorge/sneaksters-testing#38]

**Comment by Meorge** [comment]
I'll try and take a look into this, but chances are it's not something I can fix myself. My recollection is that you often have to pay an amount in order to get "whitelisted" for virus protection services.

**Comment by ZeldaPlayer29** [comment]
To add to this - for 0.3.1 on Windows - I was able to open the file the first two times without issue. After that, my computer suddenly starts glitching out on subsequent attempts to open it, keeps repeating notifications about how the file needs to be scanned before it is opened. You need to go to task manager and manually end "Sneaksters.exe" in order to stop the notifications. The only way of fixing this that I could find is to disable Windows Defender real-time protection. This is more a Windows problem, but could be a helpful reference for others.
