### ISSUE TITLE
Credits menu

### ISSUE THREAD

**Issue by ZeldaPlayer29** [Meorge/sneaksters-testing#74]
The credits menu is fine if you play through the entire thing manually and let it go back to settings itself but can get really glitchy if you click the back button whilst it is playing. The menu, for some reason, splits in two columns, and the credits resume playing again if you leave it for a few seconds. If you get back to the main menu you can end up on a screen with the Sneaksters logo, a bunch of names (without the headers) and a quit button.

In addition, clicking Credits, clicking back and then clicking credits again can lead to the credits sequence playing twice. The easiest way to explain it is the game alternates between the two sequences - so when you click credits for the second time it says "Project Lead", then goes back to where it was the first time, then goes to "Programming" etc.

**Comment by Meorge** [comment]
This sounds quite strange... I'll look into it for v0.2.1

**Comment by Meorge** [comment]
Does this happen every time you exit out of the credits? Looking at the code, I think I might see how this is happening but it relies on cancelling out at a very specific time.

**Comment by thomasdowding** [comment]
When I was trying it it was happening every time I exited out of the credits, regardless of timing. Weird how it only happens when using the back button and not when the game does it at the end of the sequence. I can record it tomorrow after work if you like to give you a better idea of what it's doing.

**Comment by Meorge** [comment]
I gather, then, that you were specifically clicking the Back button and not pressing Escape?

**Comment by thomasdowding** [comment]
Yeah that's right. I'll try pressing Escape tomorrow and get back to you.

**Comment by thomasdowding** [comment]
![Capturesnk](https://user-images.githubusercontent.com/55148125/71561619-b33c5200-2a70-11ea-8354-f7c004906467.JPG)

Using the escape key brings a completely different problem. The credits don't try to resume like they do with the back button but instead it displays the wrong menu items...

**Comment by Meorge** [comment]
I've had this issue more frequently, I think. It's basically trying to load both the main menu buttons and the settings buttons at the same time (Language and Credits are from the Settings menu, while the rest are main menu). I'll hopefully have this fixed in a future version.
Does using the Escape key consistently do this, or only sometimes? Does it ever cause the other issue to happen, or vice versa? The Escape key and Back button should map to the same code, so I'm not sure why they would be giving different results.

**Comment by thomasdowding** [comment]
Yeah, sometimes it works normally and other times it does that. The back button thing happens every time but it only happens with the back button. So yeah this sounds weird, I'll do a recording to demonstrate it.

**Comment by thomasdowding** [comment]
https://youtu.be/ZjViZtepKVI This should help demonstrate the thing with the back button. I honestly have no idea how such an issue could occur if it's using the same code as the escape key.

**Comment by Meorge** [comment]
Looks like it's simply not recognizing that the credits are being canceled. I'm not sure if this bug is something I'll be able to fix in time for v0.2.1, but I'll try to add some debugging statements so we can better diagnose the problem.

**Comment by Meorge** [comment]
Was about to fall asleep and had an epiphany as to why this is happening (or at least why the escape key and back button do different things) - cancelling the credits is specifically triggered by the escape key, the back button is never checked. This is more for me to reference later than anything, but it’s good to have a lead.

**Comment by Meorge** [comment]
It appears that in v0.3.0, you can't click on UI buttons anymore (but you can still navigate using arrow keys/WASD/joysticks/etc). In a future version (v0.4.0 perhaps?) I think I'm going to rework the menus to use a button/UI navigation system of my own creation, instead of Unity's weird thing.

In the meantime, I may fix this particular issue (the credits one) by replacing the coroutine approach with more tweening, since tweening is almost always the answer.

**Comment by Meorge** [comment]
I'm going to take this off of the v0.3.0 milestone, since fixing this will probably involve a bunch of other stuff that I'm not aiming for with v0.3.0

**Comment by Meorge** [comment]
Ok, so I think I fixed this and it was actually a *really* simple fix - way easier than I was expecting it to be. I guess we'll see if it has any issues in the future, but my bit of testing suggests it's not a problem anymore.
